# Generated by Django 3.1.7 on 2021-04-07 07:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210405_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default='/placeholder.png', max_length=255, verbose_name='image'),
        ),
    ]
